export const text = {
  en: {
    nav: {
      homes: "Homes",
      experiences: "Experiences",
      services: "Services",
      communityProjects: "Community Projects",
      volunteeringAbroad: "Volunteering Abroad",
      becomeHost: "Become a Host",
      login: "Log in",
      signup: "Sign up",
    },
    hero: {
      headline: "Stay local. Support the community.",
      description:
        "Book authentic stays in Colombia and nearby rural areas. Part of every booking supports local community projects.",
      liveThe: "Live the",
      stories: "stories",
      ofRuralColombia: "of rural Colombia",
      heroDescription: "Connect with local hosts in Colombia's countryside. Experience authentic culture, support sustainable communities, and create meaningful memories.",
      checkIn: "Check-in",
      checkOut: "Check-out",
      guests: "Guests",
      adults: "Adults",
      children: "Children",
      agesAdult: "Ages 12+",
      agesChild: "Ages 0-11",
      selectDate: "Select date",
      guest: "guest",
      guestsPlural: "guests",
      search: "Search",
    },
    map: {
      title: "Find your perfect stay",
      subtitle: "Explore accommodations on the map",
    },
    community: {
      travelWithPurpose: "Travel with purpose",
      impactDescription: "Every booking supports rural Colombian communities. Together, we're building schools, providing clean water, and creating opportunities.",
      ourImpact: "Our Impact",
      totalRaised: "Total Raised",
      treesPlanted: "Trees Planted",
      communitiesServed: "Communities Served",
      projectsCompleted: "Projects Completed",
      howItWorksTitle: "How your stay makes an impact",
      howItWorksSubtitle: "It's simple, transparent, and every contribution counts",
      step1Title: "Book Your Stay",
      step1Description: "Choose from verified rural accommodations across Colombia",
      step2Title: "Automatic Contribution",
      step2Description: "5% of your booking automatically goes to community projects",
      step3Title: "Track Impact",
      step3Description: "See exactly which projects your stay supports and their progress",
      step4Title: "Make a Difference",
      step4Description: "Your trip creates lasting positive change in rural communities",
    },
    projects: {
      title: "Current community",
      titleHighlight: "projects",
      subtitle: "Help us reach our goals and make a lasting difference in rural Colombia",
      project1Title: "School Renovation - Fusagasugá",
      project1Category: "Education",
      project1Description: "Renovating classrooms and providing new materials for 150 rural students.",
      project1Raised: "$8,450 raised",
      project1Of: "of $12,000",
      project1Complete: "70% Complete",
      project1Button: "Learn More",
      project2Title: "Clean Water System - Silvania",
      project2Category: "Infrastructure",
      project2Description: "Installing a sustainable water filtration system for 500 community members.",
      project2Raised: "$6,200 raised",
      project2Of: "of $15,000",
      project2Complete: "41% Complete",
      project2Button: "Learn More",
      project3Title: "Reforestation Initiative",
      project3Category: "Environment",
      project3Description: "Planting 5,000 native trees to restore biodiversity and prevent erosion.",
      project3Raised: "$11,500 raised",
      project3Of: "of $10,000",
      project3Complete: "✓ Funded!",
      project3Button: "View Progress",
    },
    testimonials: {
      title: "Voices from the",
      titleHighlight: "community",
      subtitle: "Real stories from the people we serve",
      person1Name: "María González",
      person1Role: "Teacher",
      person1Location: "Fusagasugá",
      person1Quote: "The school renovation has transformed our classrooms. Children now have proper desks, lighting, and materials. We've seen attendance increase by 30% and test scores improve significantly. This support means everything to our rural community.",
      person2Name: "Carlos Ramírez",
      person2Role: "Coffee Farmer",
      person2Location: "Silvania",
      person2Quote: "Hosting travelers through SPTC has given our family a sustainable income while sharing our coffee farming traditions. The community fund helped us install a clean water system that serves 80 families. It's incredible how tourism can create real change.",
    },
    cta: {
      title: "Start making a difference today",
      description: "Every stay contributes to sustainable development and community empowerment in rural Colombia",
      exploreStays: "Explore Stays",
    },
    destinations: {
      title: "Explore Colombian destinations",
      subtitle: "Authentic rural experiences across Colombia",
      fusagasuga: "Fusagasugá",
      medellin: "Medellín",
      salento: "Salento & Coffee Region",
      experiences: "experiences",
    },
    treeCounter: {
      title: "One Booking = One Tree",
      subtitle: "Reforesting Colombia's countryside",
      treesPlanted: "trees planted",
      description: "Every booking with SPTC.Rural plants one native tree in Colombia's rural communities. Together, we're restoring forests, improving biodiversity, and fighting climate change.",
      hectaresReforested: "Hectares Reforested",
      communitiesInvolved: "Communities Involved",
      nativeSpecies: "Native Species",
      learnMore: "Learn More About Our Impact",
    },
    featuredStays: {
      title: "Featured stays",
      subtitle: "Handpicked properties in Colombia",
    },
    moreStays: {
      title: "More amazing stays",
    },
    becomeHostCta: {
      title: "Become a host",
      description: "Share your space, earn income and support your community through responsible tourism.",
      button: "Get started",
    },
    footer: {
      tagline: "Connecting travelers with authentic Colombian rural experiences while supporting local communities.",
      quickLinks: "Quick Links",
      findHomes: "Find Homes",
      experiences: "Experiences",
      communityProjects: "Community Projects",
      becomeHost: "Become a Host",
      aboutUs: "About Us",
      support: "Support",
      helpCenter: "Help Center",
      cancellationPolicy: "Cancellation Policy",
      safetyInformation: "Safety Information",
      privacyPolicy: "Privacy Policy",
      termsOfService: "Terms of Service",
      contactUs: "Contact Us",
      allRightsReserved: "All rights reserved.",
      privacy: "Privacy",
      terms: "Terms",
      cookies: "Cookies",
      sitemap: "Sitemap",
    },
    homesPage: {
      title: "Find your",
      titleHighlight: "perfect stay",
      subtitle: "Discover authentic rural accommodations across Colombia",
      searchPlaceholder: "Where do you want to go?",
      filters: "Filters",
      search: "Search",
      propertyType: "Property Type",
      all: "All",
      cottage: "Cottage",
      villa: "Villa",
      finca: "Finca",
      lodge: "Lodge",
      cabin: "Cabin",
      hacienda: "Hacienda",
      priceRange: "Price Range",
      perNight: "per night",
      amenities: "Amenities",
      wifi: "WiFi",
      kitchen: "Kitchen",
      parking: "Parking",
      coffeeFarm: "Coffee Farm",
      staysIn: "stays in Colombia",
      verifiedAccommodations: "Verified rural accommodations",
      verifiedHost: "Verified Host",
      hostedBy: "Hosted by",
      guests: "guests",
      beds: "beds",
      baths: "baths",
      night: "night",
      cantFind: "Can't find what you're looking for?",
      contactHelp: "Contact us and we'll help you find the perfect accommodation",
      getInTouch: "Get in touch",
    },
    sections: {
      community: {
        title: "Support Local Communities",
        description:
          "A percentage of every booking goes directly into community funds and local development projects.",
      },
      hosts: {
        title: "Verified Local Hosts",
        description:
          "All hosts are verified through ID checks, selfie verification, and location confirmation for your peace of mind.",
      },
      experiences: {
        title: "Authentic Rural Experiences",
        description:
          "Explore coffee plantations, traditional craft workshops, local tours, and more in the heart of Colombia.",
      },
    },
    admin: {
      title: "Admin Dashboard",
      listings: "Listings",
      bookings: "Bookings",
      users: "Users & Hosts",
      funds: "Community Funds & Payouts",
      platformFee: "Platform Fee",
      verificationQueue: "Verification Queue",
    },
    experiencesPage: {
      title: "Authentic",
      titleHighlight: "experiences",
      subtitle: "Connect with local culture through immersive activities led by passionate hosts",
      allExperiences: "All Experiences",
      coffeeTours: "Coffee Tours",
      adventure: "Adventure",
      culture: "Culture & Crafts",
      food: "Food & Cooking",
      nature: "Nature & Wildlife",
      experiencesAvailable: "experiences available",
      ledByHosts: "Led by verified local hosts",
      hostedBy: "Hosted by",
      verified: "Verified",
      perPerson: "per person",
      book: "Book",
      whyBookTitle: "Why book with us?",
      whyBookSubtitle: "Every experience supports local communities and preserves traditional culture",
      localHostsTitle: "Local Hosts",
      localHostsDescription: "All experiences are led by verified local hosts who are passionate about sharing their culture and traditions",
      communityImpactTitle: "Community Impact",
      communityImpactDescription: "A portion of every booking goes directly to local community projects and development initiatives",
      qualityGuaranteedTitle: "Quality Guaranteed",
      qualityGuaranteedDescription: "Every experience is personally vetted to ensure authentic, high-quality interactions with local culture",
      ctaTitle: "Want to host an experience?",
      ctaSubtitle: "Share your skills, passion, and culture with travelers from around the world",
      ctaButton: "Become a host",
    },
    communityPage: {
      title: "Travel with",
      titleHighlight: "purpose",
      subtitle: "Every booking supports rural Colombian communities. Together, we're building schools, providing clean water, and creating opportunities.",
      totalRaised: "Total Raised",
      treesPlanted: "Trees Planted",
      communitiesServed: "Communities Served",
      projectsCompleted: "Projects Completed",
      howItWorksTitle: "How your stay makes an impact",
      howItWorksSubtitle: "It's simple, transparent, and every contribution counts",
      step1Title: "Book Your Stay",
      step1Description: "Choose from verified rural accommodations across Colombia",
      step2Title: "Automatic Contribution",
      step2Description: "5% of your booking automatically goes to community projects",
      step3Title: "Track Impact",
      step3Description: "See exactly which projects your stay supports and their progress",
      step4Title: "Make a Difference",
      step4Description: "Your trip creates lasting positive change in rural communities",
      currentProjectsTitle: "Current community projects",
      currentProjectsSubtitle: "See where your contributions are making a difference",
      impact: "Impact",
      progress: "Progress",
      of: "of",
      goal: "goal",
      supporters: "supporters",
      supportProject: "Support This Project",
      completed: "Completed",
      storiesTitle: "Stories of impact",
      storiesSubtitle: "Real stories from the communities we support",
      ctaTitle: "Start making a difference today",
      ctaSubtitle: "Book your stay and automatically contribute to rural Colombian communities",
      ctaButton: "Explore Stays",
      project1Title: "Clean Water Initiative",
      project1Location: "San Vicente, Antioquia",
      project1Category: "Infrastructure",
      project1Description: "Building clean water filtration systems for 3 rural schools serving 250 children. Providing access to safe drinking water and improving health outcomes.",
      project1Impact: "250 children will have access to clean water",
      project2Title: "Rural School Library Project",
      project2Location: "Fusagasugá, Cundinamarca",
      project2Category: "Education",
      project2Description: "Creating a community library with 500+ books and educational materials for children in remote rural areas with limited access to resources.",
      project2Impact: "150 students gain access to educational resources",
      project3Title: "Community Workshop Center",
      project3Location: "Jardín, Antioquia",
      project3Category: "Skills Development",
      project3Description: "Built a community center for teaching traditional crafts, modern skills, and hosting workshops. Now serving as a hub for cultural preservation and income generation.",
      project3Impact: "40 families trained in new income-generating skills",
      project4Title: "Sustainable Housing Project",
      project4Location: "Salento, Quindío",
      project4Category: "Housing",
      project4Description: "Renovating and improving 5 family homes with sustainable materials and techniques, providing safer living conditions and teaching eco-friendly building practices.",
      project4Impact: "5 families receive improved, safe housing",
      project5Title: "Reforestation & Tree Planting",
      project5Location: "Coffee Triangle Region",
      project5Category: "Environment",
      project5Description: "Planting native trees to restore degraded land, improve biodiversity, and combat climate change. Each booking plants one tree, creating sustainable forests for future generations.",
      project5Impact: "3,750 trees planted, 25 hectares reforested",
    },
    volunteeringPage: {
      title: "Volunteer",
      titleHighlight: "abroad",
      subtitle: "Make a lasting impact in rural Colombian communities through meaningful volunteer work",
      stat1: "Project Types",
      stat2: "Volunteers",
      stat3: "Communities",
      stat4: "Weeks",
      filterByCategory: "Filter by Category",
      allProjects: "All Projects",
      education: "Education",
      environment: "Environment",
      communityDevelopment: "Community Development",
      agriculture: "Agriculture",
      empowerment: "Women's Empowerment",
      projectsAvailable: "projects available",
      projectsSubtitle: "Authentic volunteering opportunities in rural Colombia",
      tasks: "Your Tasks",
      idealFor: "Ideal For",
      applyNow: "Apply Now",
      whyVolunteerTitle: "Why volunteer with us?",
      whyVolunteerSubtitle: "Transform communities while transforming yourself",
      benefit1Title: "Real Impact",
      benefit1Description: "Work directly with rural communities on projects that create lasting positive change",
      benefit2Title: "Cultural Immersion",
      benefit2Description: "Live and work alongside locals, experiencing authentic Colombian culture and traditions",
      benefit3Title: "Personal Growth",
      benefit3Description: "Develop new skills, gain global perspective, and create meaningful connections",
      ctaTitle: "Ready to make a difference?",
      ctaSubtitle: "Join our volunteer community and help build a better future for rural Colombia",
      ctaButton: "Get Started",
      project1Title: "Teaching & English Assistance in Rural Schools",
      project1Description: "Volunteers help out in rural primary or secondary schools teaching basic English, working with youth mentors, and running interactive workshops.",
      project1Tasks: "Assist local teachers, create interactive activities, language games, mentor youth, support after-school clubs",
      project1Duration: "2-12 weeks",
      project1IdealFor: "Teachers, students, anyone passionate about education",
      project1Location: "Rural communities nationwide",
      project2Title: "Youth Mentoring & Outreach in Rural Communities",
      project2Description: "Work with rural youth groups, at-risk teens, and community centres in smaller towns outside major cities.",
      project2Tasks: "Lead mentoring sessions, life skills workshops, sports or creative activities, integrate with local coordinator network",
      project2Duration: "1-8 weeks",
      project2IdealFor: "Youth workers, counselors, sports coaches",
      project2Location: "Fusagasugá region",
      project3Title: "Environmental Conservation & Reforestation Projects",
      project3Description: "Volunteers help restore rural ecosystems, plant trees, maintain trails, and work on farms implementing sustainable practices.",
      project3Tasks: "Tree planting, trail maintenance, habitat monitoring, community education about sustainability",
      project3Duration: "1-6 weeks",
      project3IdealFor: "Nature lovers, environmental science students",
      project3Location: "Rural mountainous regions",
      project4Title: "Organic Farming & Sustainable Agriculture Support",
      project4Description: "Assist small rural farms (coffee, sugar-cane, permaculture) in countryside regions.",
      project4Tasks: "Harvesting, assisting local farmers, planting, maintenance, environmentally friendly techniques",
      project4Duration: "2-4 weeks",
      project4IdealFor: "Agriculture enthusiasts, sustainable living advocates",
      project4Location: "Coffee growing regions",
      project5Title: "Rural Community Development & Infrastructure Aid",
      project5Description: "Help build or repair community infrastructure in rural towns: schools, community centres, rural homes.",
      project5Tasks: "Construction aid, painting, garden building, community landscaping, basic maintenance",
      project5Duration: "1-4 weeks",
      project5IdealFor: "Builders, DIY enthusiasts, practical hands-on workers",
      project5Location: "Small rural towns",
      project6Title: "Cultural Heritage & Indigenous Community Projects",
      project6Description: "Work with indigenous or small rural community groups helping preserve culture, language, crafts, and eco-tourism models.",
      project6Tasks: "Assist with community tourism initiatives, help organize craft workshops, language exchange, site interpretation",
      project6Duration: "2-6 weeks",
      project6IdealFor: "Anthropology students, cultural enthusiasts, artisans",
      project6Location: "Indigenous communities",
      project7Title: "Animal & Wildlife Conservation in Rural Areas",
      project7Description: "Volunteer at rural sanctuaries and wildlife rescue centres in remote areas of Colombia.",
      project7Tasks: "Caring for animals, habitat clean-ups, educational outreach, environmental monitoring",
      project7Duration: "1-4 weeks",
      project7IdealFor: "Animal lovers, veterinary students, wildlife enthusiasts",
      project7Location: "Rural sanctuaries nationwide",
      project8Title: "Eco-Tourism & Permaculture Project Support",
      project8Description: "Assist eco-villages, rural guest-houses, and permaculture farms; combine volunteering with sustainable tourism.",
      project8Tasks: "Garden work, guest-house upkeep, guiding nature walks, assisting in guest-experience side",
      project8Duration: "1-3 weeks",
      project8IdealFor: "Eco-tourism enthusiasts, permaculture learners",
      project8Location: "San Agustín region",
      project9Title: "Spanish Teaching + Cultural Exchange in Small Towns",
      project9Description: "Volunteers teach Spanish classes, engage in cultural exchange, and act as language buddies.",
      project9Tasks: "Classroom/one-on-one teaching, conversation groups, cultural workshops, supporting local language initiatives",
      project9Duration: "2-8 weeks",
      project9IdealFor: "Language teachers, Spanish learners, cultural ambassadors",
      project9Location: "Small towns nationwide",
      project10Title: "Women's Empowerment & Community Entrepreneurship",
      project10Description: "Program focused on supporting rural women's groups, cooperatives, and community-led tourism ventures.",
      project10Tasks: "Assist with business training, marketing support, tourism-service training, mentor groups of women",
      project10Duration: "2-6 weeks",
      project10IdealFor: "Business professionals, women's rights advocates, entrepreneurs",
      project10Location: "Rural women's cooperatives",
    },
    searchPage: {
      hideMap: "Hide Map",
      showOnMap: "Show on Map",
      filterBy: "Filter by",
      clearAll: "Clear all",
      pricePerNight: "Price per night (USD)",
      min: "Min",
      max: "Max",
      ruralExperience: "Rural Experience",
      coffeeFarmExperience: "Coffee Farm Experience",
      mountainViews: "Mountain Views",
      ecoFriendly: "Eco-Friendly",
      traditionalArchitecture: "Traditional Architecture",
      wifiAvailable: "WiFi Available",
      mealsIncluded: "Meals Included",
      freeParking: "Free Parking",
      natureTrails: "Nature Trails",
      propertyType: "Property Type",
      countryHouses: "Country Houses",
      traditionalHomes: "Traditional Homes",
      coffeeFarms: "Coffee Farms",
      mountainCabins: "Mountain Cabins",
      ecoLodges: "Eco Lodges",
      propertiesFound: "properties found",
      authenticRuralStays: "Authentic rural stays in Colombia's countryside",
      recommended: "Recommended",
      priceLowToHigh: "Price: Low to High",
      priceHighToLow: "Price: High to Low",
      highestRated: "Highest Rated",
      countryHouse: "Country House",
      cabin: "Cabin",
      traditionalHome: "Traditional Home",
      fromCenter: "from center",
      superhost: "Superhost",
      freeCancellation: "Free cancellation",
      bedroom: "bedroom(s)",
      bed: "bed(s)",
      bathroom: "bathroom(s)",
      hostedBy: "Hosted by",
      breakfastIncluded: "Breakfast included",
      night: "night",
      seeAvailability: "See availability",
      checkIn: "Check in",
      checkOut: "Check out",
      adults: "adults",
      children: "children",
    },
    hostOnboarding: {
      welcome: "Welcome to SPTC.Rural",
      welcomeSubtitle: "Join our community of trusted hosts",
      step1Title: "Verify Your Identity",
      step1Subtitle: "We need to confirm you are who you say you are",
      step2Title: "Face Verification",
      step2Subtitle: "Match your face to your ID document",
      step3Title: "Property Photos",
      step3Subtitle: "Upload 2 photos of your property with location data",
      step4Title: "Review & Submit",
      step4Subtitle: "Review your information before submission",
      uploadID: "Upload Passport or ID",
      uploadIDDescription: "Please upload a clear photo of your government-issued passport or national ID card",
      dragDrop: "Drag and drop your ID here, or click to browse",
      supportedFormats: "Supported formats: JPG, PNG, PDF (max 10MB)",
      faceVerification: "Face Verification",
      faceVerificationDescription: "Take a selfie to verify your identity matches your ID document",
      startCamera: "Start Camera",
      retakePhoto: "Retake Photo",
      photoLooksGood: "Photo looks good!",
      propertyPhotos: "Property Photos",
      propertyPhotosDescription: "Upload 2 high-quality photos of your property. Location data will be automatically captured.",
      photo: "Photo",
      uploadPhoto: "Upload Photo",
      locationCaptured: "Location captured",
      locationRequired: "Location data required - please enable location services",
      allPhotosRequired: "All 2 photos required",
      reviewInfo: "Review Your Information",
      personalDetails: "Personal Details",
      verificationStatus: "Verification Status",
      verified: "Verified",
      pending: "Pending Review",
      propertyDetails: "Property Details",
      photosUploaded: "photos uploaded",
      locationVerified: "Location verified",
      submit: "Submit for Review",
      submitting: "Submitting...",
      successTitle: "Application Submitted!",
      successMessage: "We're reviewing your application. You'll hear from us within 24-48 hours.",
      goToDashboard: "Go to Dashboard",
      continue: "Continue",
      back: "Back",
      skip: "Skip for now",
    },
    hostDashboard: {
      welcome: "Welcome back",
      dashboard: "Dashboard",
      bookings: "Bookings",
      earnings: "Earnings",
      messages: "Messages",
      property: "Property",
      settings: "Settings",
      logout: "Logout",
      upcomingBookings: "Upcoming Bookings",
      pastBookings: "Past Bookings",
      noBookings: "No bookings yet",
      checkIn: "Check-in",
      checkOut: "Check-out",
      guests: "Guests",
      total: "Total",
      pending: "Pending",
      confirmed: "Confirmed",
      cancelled: "Cancelled",
      viewDetails: "View Details",
      messageGuest: "Message Guest",
      totalEarnings: "Total Earnings",
      thisMonth: "This Month",
      lastMonth: "Last Month",
      available: "Available for Payout",
      requestPayout: "Request Payout",
      payoutHistory: "Payout History",
      date: "Date",
      amount: "Amount",
      status: "Status",
      paid: "Paid",
      processing: "Processing",
      recentMessages: "Recent Messages",
      newMessage: "New message",
      typeMessage: "Type your message...",
      send: "Send",
      propertyStats: "Property Statistics",
      views: "Views",
      bookingRate: "Booking Rate",
      avgRating: "Average Rating",
      responseTime: "Response Time",
      hours: "hours",
      updateProperty: "Update Property",
      manageAvailability: "Manage Availability",
      quickActions: "Quick Actions",
      totalBookings: "Total Bookings",
      activeListings: "Active Listings",
      pendingPayouts: "Pending Payouts",
    },
    hostPricing: {
      title: "Host Admin Panel",
      subtitle: "Manage your pricing and listing photos",
      pricing: "Pricing",
      photos: "Photos",
      baseRate: "Base Rate",
      baseRateDescription: "Set your default nightly price",
      basePricePerNight: "Base Price per Night",
      calendarPricing: "Calendar Pricing",
      pricingRules: "Pricing Rules",
      addRule: "Add Rule",
      noRules: "No pricing rules yet",
      clickToAdd: "Click + to add a rule",
      customPrices: "Custom Prices",
      uploadPhotos: "Upload Listing Photos",
      uploadDescription: "Upload high-quality images of your property. Supported formats: JPG, PNG, WebP (max 10MB each)",
      chooseFiles: "Choose Files",
      photoGallery: "Photo Gallery",
      carousel: "Carousel",
      viewAdvert: "View Advert",
      noPhotos: "No photos uploaded yet",
      uploadToSee: "Upload photos to see them here",
      yourListing: "Your Property Listing",
      previewDescription: "This is how your listing will appear on the website",
      pricePerNight: "Price per night",
      rating: "Rating",
      photosUploaded: "photos uploaded",
      photo: "photo",
      setCustomPrice: "Set Custom Price",
      date: "Date",
      currentPrice: "Current Price",
      customPriceLabel: "Custom Price ($)",
      reasonOptional: "Reason (Optional)",
      savePrice: "Save Price",
      addPricingRule: "Add Pricing Rule",
      editPricingRule: "Edit Pricing Rule",
      ruleName: "Rule Name",
      type: "Type",
      value: "Value",
      startDate: "Start Date",
      endDate: "End Date",
      appliesTo: "Applies To",
      allDays: "All Days",
      weekendsOnly: "Weekends Only",
      weekdaysOnly: "Weekdays Only",
      holidaysOnly: "Holidays Only",
      percentageIncrease: "Percentage Increase/Decrease",
      fixedPrice: "Fixed Price",
      discount: "Discount (%)",
      preview: "Preview",
      afterRule: "After Rule",
      updateRule: "Update Rule",
      addRuleButton: "Add Rule",
      cancel: "Cancel",
      lastUpdated: "Last Updated",
      justNow: "Just now",
    },
    hostMessages: {
      title: "Messages",
      subtitle: "Communicate with your guests",
      allMessages: "All Messages",
      unread: "Unread",
      archived: "Archived",
      searchMessages: "Search messages...",
      newConversation: "New Conversation",
      selectGuest: "Select a guest to start messaging",
      guestName: "Guest Name",
      bookingDates: "Booking Dates",
      attachFile: "Attach File",
      sendMessage: "Send Message",
      online: "Online",
      offline: "Offline",
      typing: "typing...",
      lastSeen: "Last seen",
      markAsRead: "Mark as Read",
      archive: "Archive",
      delete: "Delete",
      noMessages: "No messages yet",
      startConversation: "Start a conversation with your guests",
    },
  },
  es: {
    nav: {
      homes: "Casas",
      experiences: "Experiencias",
      services: "Servicios",
      communityProjects: "Proyectos Comunitarios",
      volunteeringAbroad: "Voluntariado en el Extranjero",
      becomeHost: "Ser Anfitrión",
      login: "Iniciar sesión",
      signup: "Registrarse",
    },
    hero: {
      headline: "Quédate local. Apoya la comunidad.",
      description:
        "Reserva estadías auténticas en Colombia y áreas rurales cercanas. Parte de cada reserva apoya proyectos comunitarios locales.",
      liveThe: "Vive las",
      stories: "historias",
      ofRuralColombia: "de la Colombia rural",
      heroDescription: "Conéctate con anfitriones locales en el campo colombiano. Experimenta la cultura auténtica, apoya comunidades sostenibles y crea recuerdos significativos.",
      checkIn: "Entrada",
      checkOut: "Salida",
      guests: "Huéspedes",
      adults: "Adultos",
      children: "Niños",
      agesAdult: "12+ años",
      agesChild: "0-11 años",
      selectDate: "Seleccionar fecha",
      guest: "huésped",
      guestsPlural: "huéspedes",
      search: "Buscar",
    },
    map: {
      title: "Encuentra tu estadía perfecta",
      subtitle: "Explora alojamientos en el mapa",
    },
    community: {
      travelWithPurpose: "Viaja con propósito",
      impactDescription: "Cada reserva apoya a las comunidades rurales colombianas. Juntos, estamos construyendo escuelas, proporcionando agua limpia y creando oportunidades.",
      ourImpact: "Nuestro Impacto",
      totalRaised: "Total Recaudado",
      treesPlanted: "Árboles Plantados",
      communitiesServed: "Comunidades Servidas",
      projectsCompleted: "Proyectos Completados",
      howItWorksTitle: "Cómo tu estadía genera impacto",
      howItWorksSubtitle: "Es simple, transparente y cada contribución cuenta",
      step1Title: "Reserva Tu Estadía",
      step1Description: "Elige entre alojamientos rurales verificados en toda Colombia",
      step2Title: "Contribución Automática",
      step2Description: "El 5% de tu reserva va automáticamente a proyectos comunitarios",
      step3Title: "Rastrea el Impacto",
      step3Description: "Ve exactamente qué proyectos apoya tu estadía y su progreso",
      step4Title: "Haz la Diferencia",
      step4Description: "Tu viaje crea un cambio positivo duradero en comunidades rurales",
    },
    projects: {
      title: "Proyectos comunitarios",
      titleHighlight: "actuales",
      subtitle: "Ayúdanos a alcanzar nuestras metas y hacer una diferencia duradera en la Colombia rural",
      project1Title: "Renovación Escolar - Fusagasugá",
      project1Category: "Educación",
      project1Description: "Renovando aulas y proporcionando nuevos materiales para 150 estudiantes rurales.",
      project1Raised: "$8,450 recaudados",
      project1Of: "de $12,000",
      project1Complete: "70% Completado",
      project1Button: "Más Información",
      project2Title: "Sistema de Agua Limpia - Silvania",
      project2Category: "Infraestructura",
      project2Description: "Instalando un sistema de filtración de agua sostenible para 500 miembros de la comunidad.",
      project2Raised: "$6,200 recaudados",
      project2Of: "de $15,000",
      project2Complete: "41% Completado",
      project2Button: "Más Información",
      project3Title: "Iniciativa de Reforestación",
      project3Category: "Medio Ambiente",
      project3Description: "Plantando 5,000 árboles nativos para restaurar la biodiversidad y prevenir la erosión.",
      project3Raised: "$11,500 recaudados",
      project3Of: "de $10,000",
      project3Complete: "✓ ¡Financiado!",
      project3Button: "Ver Progreso",
    },
    testimonials: {
      title: "Voces de la",
      titleHighlight: "comunidad",
      subtitle: "Historias reales de las personas a las que servimos",
      person1Name: "María González",
      person1Role: "Maestra",
      person1Location: "Fusagasugá",
      person1Quote: "La renovación escolar ha transformado nuestras aulas. Los niños ahora tienen escritorios adecuados, iluminación y materiales. Hemos visto un aumento del 30% en la asistencia y una mejora significativa en los puntajes de las pruebas. Este apoyo lo es todo para nuestra comunidad rural.",
      person2Name: "Carlos Ramírez",
      person2Role: "Agricultor de Café",
      person2Location: "Silvania",
      person2Quote: "Alojar viajeros a través de SPTC le ha dado a nuestra familia un ingreso sostenible mientras compartimos nuestras tradiciones cafeteras. El fondo comunitario nos ayudó a instalar un sistema de agua limpia que sirve a 80 familias. Es increíble cómo el turismo puede crear un cambio real.",
    },
    cta: {
      title: "Comienza a marcar la diferencia hoy",
      description: "Cada estadía contribuye al desarrollo sostenible y el empoderamiento comunitario en la Colombia rural",
      exploreStays: "Explorar Estadías",
    },
    destinations: {
      title: "Explora destinos colombianos",
      subtitle: "Experiencias rurales auténticas en toda Colombia",
      fusagasuga: "Fusagasugá",
      medellin: "Medellín",
      salento: "Salento y Región Cafetera",
      experiences: "experiencias",
    },
    treeCounter: {
      title: "Una Reserva = Un Árbol",
      subtitle: "Reforestando el campo colombiano",
      treesPlanted: "árboles plantados",
      description: "Cada reserva con SPTC.Rural planta un árbol nativo en las comunidades rurales de Colombia. Juntos, estamos restaurando bosques, mejorando la biodiversidad y luchando contra el cambio climático.",
      hectaresReforested: "Hectáreas Reforestadas",
      communitiesInvolved: "Comunidades Involucradas",
      nativeSpecies: "Especies Nativas",
      learnMore: "Más Información Sobre Nuestro Impacto",
    },
    featuredStays: {
      title: "Estadías destacadas",
      subtitle: "Propiedades seleccionadas en Colombia",
    },
    moreStays: {
      title: "Más estadías increíbles",
    },
    becomeHostCta: {
      title: "Conviértete en anfitrión",
      description: "Comparte tu espacio, genera ingresos y apoya a tu comunidad a través del turismo responsable.",
      button: "Comenzar",
    },
    footer: {
      tagline: "Conectando viajeros con experiencias rurales auténticas colombianas mientras apoyamos a las comunidades locales.",
      quickLinks: "Enlaces Rápidos",
      findHomes: "Buscar Casas",
      experiences: "Experiencias",
      communityProjects: "Proyectos Comunitarios",
      becomeHost: "Ser Anfitrión",
      aboutUs: "Sobre Nosotros",
      support: "Soporte",
      helpCenter: "Centro de Ayuda",
      cancellationPolicy: "Política de Cancelación",
      safetyInformation: "Información de Seguridad",
      privacyPolicy: "Política de Privacidad",
      termsOfService: "Términos de Servicio",
      contactUs: "Contáctanos",
      allRightsReserved: "Todos los derechos reservados.",
      privacy: "Privacidad",
      terms: "Términos",
      cookies: "Cookies",
      sitemap: "Mapa del Sitio",
    },
    homesPage: {
      title: "Encuentra tu",
      titleHighlight: "estadía perfecta",
      subtitle: "Descubre alojamientos rurales auténticos en toda Colombia",
      searchPlaceholder: "¿A dónde quieres ir?",
      filters: "Filtros",
      search: "Buscar",
      propertyType: "Tipo de Propiedad",
      all: "Todos",
      cottage: "Cabaña",
      villa: "Villa",
      finca: "Finca",
      lodge: "Posada",
      cabin: "Cabaña",
      hacienda: "Hacienda",
      priceRange: "Rango de Precio",
      perNight: "por noche",
      amenities: "Comodidades",
      wifi: "WiFi",
      kitchen: "Cocina",
      parking: "Estacionamiento",
      coffeeFarm: "Finca Cafetera",
      staysIn: "estadías en Colombia",
      verifiedAccommodations: "Alojamientos rurales verificados",
      verifiedHost: "Anfitrión Verificado",
      hostedBy: "Hospedado por",
      guests: "huéspedes",
      beds: "camas",
      baths: "baños",
      night: "noche",
      cantFind: "¿No encuentras lo que buscas?",
      contactHelp: "Contáctanos y te ayudaremos a encontrar el alojamiento perfecto",
      getInTouch: "Contáctanos",
    },
    sections: {
      community: {
        title: "Apoya las Comunidades Locales",
        description:
          "Un porcentaje de cada reserva va directamente a fondos comunitarios y proyectos de desarrollo local.",
      },
      hosts: {
        title: "Anfitriones Locales Verificados",
        description:
          "Todos los anfitriones son verificados mediante controles de identificación, verificación de selfie y confirmación de ubicación para tu tranquilidad.",
      },
      experiences: {
        title: "Experiencias Rurales Auténticas",
        description:
          "Explora plantaciones de café, talleres de artesanía tradicional, tours locales y más en el corazón de Colombia.",
      },
    },
    admin: {
      title: "Panel de Administración",
      listings: "Listados",
      bookings: "Reservas",
      users: "Usuarios y Anfitriones",
      funds: "Fondos Comunitarios y Pagos",
      platformFee: "Tarifa de Plataforma",
      verificationQueue: "Cola de Verificación",
    },
    experiencesPage: {
      title: "Experiencias",
      titleHighlight: "auténticas",
      subtitle: "Conecta con la cultura local a través de actividades inmersivas dirigidas por anfitriones apasionados",
      allExperiences: "Todas las Experiencias",
      coffeeTours: "Tours de Café",
      adventure: "Aventura",
      culture: "Cultura y Artesanías",
      food: "Comida y Cocina",
      nature: "Naturaleza y Vida Silvestre",
      experiencesAvailable: "experiencias disponibles",
      ledByHosts: "Dirigidas por anfitriones locales verificados",
      hostedBy: "Hospedado por",
      verified: "Verificado",
      perPerson: "por persona",
      book: "Reservar",
      whyBookTitle: "¿Por qué reservar con nosotros?",
      whyBookSubtitle: "Cada experiencia apoya a las comunidades locales y preserva la cultura tradicional",
      localHostsTitle: "Anfitriones Locales",
      localHostsDescription: "Todas las experiencias son dirigidas por anfitriones locales verificados que son apasionados por compartir su cultura y tradiciones",
      communityImpactTitle: "Impacto Comunitario",
      communityImpactDescription: "Una parte de cada reserva va directamente a proyectos comunitarios locales e iniciativas de desarrollo",
      qualityGuaranteedTitle: "Calidad Garantizada",
      qualityGuaranteedDescription: "Cada experiencia es verificada personalmente para asegurar interacciones auténticas y de alta calidad con la cultura local",
      ctaTitle: "¿Quieres organizar una experiencia?",
      ctaSubtitle: "Comparte tus habilidades, pasión y cultura con viajeros de todo el mundo",
      ctaButton: "Conviértete en anfitrión",
    },
    communityPage: {
      title: "Viaja con",
      titleHighlight: "propósito",
      subtitle: "Cada reserva apoya a las comunidades rurales colombianas. Juntos, estamos construyendo escuelas, proporcionando agua limpia y creando oportunidades.",
      totalRaised: "Total Recaudado",
      treesPlanted: "Árboles Plantados",
      communitiesServed: "Comunidades Servidas",
      projectsCompleted: "Proyectos Completados",
      howItWorksTitle: "Cómo tu estadía genera impacto",
      howItWorksSubtitle: "Es simple, transparente y cada contribución cuenta",
      step1Title: "Reserva Tu Estadía",
      step1Description: "Elige entre alojamientos rurales verificados en toda Colombia",
      step2Title: "Contribución Automática",
      step2Description: "El 5% de tu reserva va automáticamente a proyectos comunitarios",
      step3Title: "Rastrea el Impacto",
      step3Description: "Ve exactamente qué proyectos apoya tu estadía y su progreso",
      step4Title: "Haz la Diferencia",
      step4Description: "Tu viaje crea un cambio positivo duradero en comunidades rurales",
      currentProjectsTitle: "Proyectos comunitarios actuales",
      currentProjectsSubtitle: "Ve dónde tus contribuciones están marcando la diferencia",
      impact: "Impacto",
      progress: "Progreso",
      of: "de",
      goal: "meta",
      supporters: "seguidores",
      supportProject: "Apoyar Este Proyecto",
      completed: "Completado",
      storiesTitle: "Historias de impacto",
      storiesSubtitle: "Historias reales de las comunidades que apoyamos",
      ctaTitle: "Comienza a marcar la diferencia hoy",
      ctaSubtitle: "Reserva tu estadía y contribuye automáticamente a las comunidades rurales colombianas",
      ctaButton: "Explorar Estadías",
      project1Title: "Iniciativa de Agua Limpia",
      project1Location: "San Vicente, Antioquia",
      project1Category: "Infraestructura",
      project1Description: "Construyendo sistemas de filtración de agua limpia para 3 escuelas rurales que atienden a 250 niños. Proporcionando acceso a agua potable segura y mejorando los resultados de salud.",
      project1Impact: "250 niños tendrán acceso a agua limpia",
      project2Title: "Proyecto de Biblioteca Escolar Rural",
      project2Location: "Fusagasugá, Cundinamarca",
      project2Category: "Educación",
      project2Description: "Creando una biblioteca comunitaria con más de 500 libros y materiales educativos para niños en áreas rurales remotas con acceso limitado a recursos.",
      project2Impact: "150 estudiantes obtienen acceso a recursos educativos",
      project3Title: "Centro de Talleres Comunitarios",
      project3Location: "Jardín, Antioquia",
      project3Category: "Desarrollo de Habilidades",
      project3Description: "Construimos un centro comunitario para enseñar artesanías tradicionales, habilidades modernas y organizar talleres. Ahora sirve como centro para la preservación cultural y la generación de ingresos.",
      project3Impact: "40 familias capacitadas en nuevas habilidades generadoras de ingresos",
      project4Title: "Proyecto de Vivienda Sostenible",
      project4Location: "Salento, Quindío",
      project4Category: "Vivienda",
      project4Description: "Renovando y mejorando 5 hogares familiares con materiales y técnicas sostenibles, proporcionando condiciones de vida más seguras y enseñando prácticas de construcción ecológicas.",
      project4Impact: "5 familias reciben vivienda mejorada y segura",
      project5Title: "Reforestación y Plantación de Árboles",
      project5Location: "Región del Triángulo del Café",
      project5Category: "Medio Ambiente",
      project5Description: "Plantando árboles nativos para restaurar tierras degradadas, mejorar la biodiversidad y combatir el cambio climático. Cada reserva planta un árbol, creando bosques sostenibles para las generaciones futuras.",
      project5Impact: "3,750 árboles plantados, 25 hectáreas reforestadas",
    },
    volunteeringPage: {
      title: "Voluntariado en el",
      titleHighlight: "extranjero",
      subtitle: "Genera un impacto duradero en las comunidades rurales colombianas a través de un trabajo voluntario significativo",
      stat1: "Tipos de Proyectos",
      stat2: "Voluntarios",
      stat3: "Comunidades",
      stat4: "Semanas",
      filterByCategory: "Filtrar por Categoría",
      allProjects: "Todos los Proyectos",
      education: "Educación",
      environment: "Medio Ambiente",
      communityDevelopment: "Desarrollo Comunitario",
      agriculture: "Agricultura",
      empowerment: "Empoderamiento de la Mujer",
      projectsAvailable: "proyectos disponibles",
      projectsSubtitle: "Oportunidades auténticas de voluntariado en la Colombia rural",
      tasks: "Tus Tareas",
      idealFor: "Ideal Para",
      applyNow: "Aplicar Ahora",
      whyVolunteerTitle: "¿Por qué ser voluntario con nosotros?",
      whyVolunteerSubtitle: "Transforma comunidades mientras te transformas a ti mismo",
      benefit1Title: "Impacto Real",
      benefit1Description: "Trabaja directamente con comunidades rurales en proyectos que crean un cambio positivo duradero",
      benefit2Title: "Inmersión Cultural",
      benefit2Description: "Vive y trabaja junto a los locales, experimentando la auténtica cultura y tradiciones colombianas",
      benefit3Title: "Crecimiento Personal",
      benefit3Description: "Desarrolla nuevas habilidades, obtén perspectiva global y crea conexiones significativas",
      ctaTitle: "¿Listo para marcar la diferencia?",
      ctaSubtitle: "Únete a nuestra comunidad de voluntarios y ayuda a construir un mejor futuro para la Colombia rural",
      ctaButton: "Comenzar",
      project1Title: "Enseñanza y Asistencia de Inglés en Escuelas Rurales",
      project1Description: "Los voluntarios ayudan en escuelas primarias o secundarias rurales enseñando inglés básico, trabajando con mentores juveniles y organizando talleres interactivos.",
      project1Tasks: "Asistir a maestros locales, crear actividades interactivas, juegos de idiomas, mentoría juvenil, apoyar clubes extracurriculares",
      project1Duration: "2-12 semanas",
      project1IdealFor: "Maestros, estudiantes, cualquier persona apasionada por la educación",
      project1Location: "Comunidades rurales a nivel nacional",
      project2Title: "Mentoría Juvenil y Alcance en Comunidades Rurales",
      project2Description: "Trabaja con grupos de jóvenes rurales, adolescentes en riesgo y centros comunitarios en pueblos pequeños fuera de las grandes ciudades.",
      project2Tasks: "Dirigir sesiones de mentoría, talleres de habilidades para la vida, actividades deportivas o creativas, integrarse con la red de coordinadores locales",
      project2Duration: "1-8 semanas",
      project2IdealFor: "Trabajadores juveniles, consejeros, entrenadores deportivos",
      project2Location: "Región de Fusagasugá",
      project3Title: "Proyectos de Conservación Ambiental y Reforestación",
      project3Description: "Los voluntarios ayudan a restaurar ecosistemas rurales, plantar árboles, mantener senderos y trabajar en granjas implementando prácticas sostenibles.",
      project3Tasks: "Plantación de árboles, mantenimiento de senderos, monitoreo de hábitats, educación comunitaria sobre sostenibilidad",
      project3Duration: "1-6 semanas",
      project3IdealFor: "Amantes de la naturaleza, estudiantes de ciencias ambientales",
      project3Location: "Regiones montañosas rurales",
      project4Title: "Agricultura Orgánica y Apoyo a la Agricultura Sostenible",
      project4Description: "Asiste a pequeñas granjas rurales (café, caña de azúcar, permacultura) en regiones campesinas.",
      project4Tasks: "Cosecha, asistencia a agricultores locales, plantación, mantenimiento, técnicas amigables con el medio ambiente",
      project4Duration: "2-4 semanas",
      project4IdealFor: "Entusiastas de la agricultura, defensores de la vida sostenible",
      project4Location: "Regiones cafeteras",
      project5Title: "Desarrollo Comunitario Rural y Ayuda a la Infraestructura",
      project5Description: "Ayuda a construir o reparar infraestructura comunitaria en pueblos rurales: escuelas, centros comunitarios, hogares rurales.",
      project5Tasks: "Ayuda en construcción, pintura, construcción de jardines, paisajismo comunitario, mantenimiento básico",
      project5Duration: "1-4 semanas",
      project5IdealFor: "Constructores, entusiastas del bricolaje, trabajadores prácticos",
      project5Location: "Pequeños pueblos rurales",
      project6Title: "Proyectos de Patrimonio Cultural y Comunidades Indígenas",
      project6Description: "Trabaja con grupos comunitarios indígenas o rurales pequeños ayudando a preservar la cultura, el idioma, las artesanías y los modelos de ecoturismo.",
      project6Tasks: "Asistir con iniciativas de turismo comunitario, ayudar a organizar talleres de artesanía, intercambio de idiomas, interpretación de sitios",
      project6Duration: "2-6 semanas",
      project6IdealFor: "Estudiantes de antropología, entusiastas culturales, artesanos",
      project6Location: "Comunidades indígenas",
      project7Title: "Conservación de Animales y Vida Silvestre en Áreas Rurales",
      project7Description: "Voluntariado en santuarios rurales y centros de rescate de vida silvestre en áreas remotas de Colombia.",
      project7Tasks: "Cuidado de animales, limpieza de hábitats, divulgación educativa, monitoreo ambiental",
      project7Duration: "1-4 semanas",
      project7IdealFor: "Amantes de los animales, estudiantes de veterinaria, entusiastas de la vida silvestre",
      project7Location: "Santuarios rurales a nivel nacional",
      project8Title: "Apoyo a Proyectos de Ecoturismo y Permacultura",
      project8Description: "Asiste a ecoaldeas, casas de huéspedes rurales y granjas de permacultura; combina el voluntariado con el turismo sostenible.",
      project8Tasks: "Trabajo de jardín, mantenimiento de casas de huéspedes, guía de caminatas naturales, asistencia en el lado de la experiencia del huésped",
      project8Duration: "1-3 semanas",
      project8IdealFor: "Entusiastas del ecoturismo, aprendices de permacultura",
      project8Location: "Región de San Agustín",
      project9Title: "Enseñanza de Español + Intercambio Cultural en Pueblos Pequeños",
      project9Description: "Los voluntarios enseñan clases de español, participan en el intercambio cultural y actúan como compañeros de idiomas.",
      project9Tasks: "Enseñanza en aula/uno a uno, grupos de conversación, talleres culturales, apoyo a iniciativas de idiomas locales",
      project9Duration: "2-8 semanas",
      project9IdealFor: "Profesores de idiomas, aprendices de español, embajadores culturales",
      project9Location: "Pueblos pequeños a nivel nacional",
      project10Title: "Empoderamiento de la Mujer y Emprendimiento Comunitario",
      project10Description: "Programa enfocado en apoyar grupos de mujeres rurales, cooperativas y emprendimientos turísticos liderados por la comunidad.",
      project10Tasks: "Asistir con capacitación empresarial, apoyo de marketing, capacitación en servicios turísticos, mentoría de grupos de mujeres",
      project10Duration: "2-6 semanas",
      project10IdealFor: "Profesionales de negocios, defensores de los derechos de las mujeres, emprendedores",
      project10Location: "Cooperativas de mujeres rurales",
    },
    searchPage: {
      hideMap: "Ocultar Mapa",
      showOnMap: "Mostrar en el Mapa",
      filterBy: "Filtrar por",
      clearAll: "Limpiar todo",
      pricePerNight: "Precio por noche (USD)",
      min: "Mín",
      max: "Máx",
      ruralExperience: "Experiencia Rural",
      coffeeFarmExperience: "Experiencia en Finca Cafetera",
      mountainViews: "Vistas a la Montaña",
      ecoFriendly: "Eco-Amigable",
      traditionalArchitecture: "Arquitectura Tradicional",
      wifiAvailable: "WiFi Disponible",
      mealsIncluded: "Comidas Incluidas",
      freeParking: "Estacionamiento Gratuito",
      natureTrails: "Senderos Naturales",
      propertyType: "Tipo de Propiedad",
      countryHouses: "Casas de Campo",
      traditionalHomes: "Casas Tradicionales",
      coffeeFarms: "Fincas Cafeteras",
      mountainCabins: "Cabañas de Montaña",
      ecoLodges: "Eco Posadas",
      propertiesFound: "propiedades encontradas",
      authenticRuralStays: "Estadías rurales auténticas en el campo colombiano",
      recommended: "Recomendado",
      priceLowToHigh: "Precio: Menor a Mayor",
      priceHighToLow: "Precio: Mayor a Menor",
      highestRated: "Mejor Calificado",
      countryHouse: "Casa de Campo",
      cabin: "Cabaña",
      traditionalHome: "Casa Tradicional",
      fromCenter: "del centro",
      superhost: "Superanfitrión",
      freeCancellation: "Cancelación gratuita",
      bedroom: "habitación(es)",
      bed: "cama(s)",
      bathroom: "baño(s)",
      hostedBy: "Hospedado por",
      breakfastIncluded: "Desayuno incluido",
      night: "noche",
      seeAvailability: "Ver disponibilidad",
      checkIn: "Entrada",
      checkOut: "Salida",
      adults: "adultos",
      children: "niños",
    },
    hostOnboarding: {
      welcome: "Bienvenido a SPTC.Rural",
      welcomeSubtitle: "Únete a nuestra comunidad de anfitriones confiables",
      step1Title: "Verifica tu identidad",
      step1Subtitle: "Necesitamos confirmar que eres quien dices ser",
      step2Title: "Verificación facial",
      step2Subtitle: "Compara tu rostro con tu documento de identidad",
      step3Title: "Fotos de la propiedad",
      step3Subtitle: "Sube 2 fotos de tu propiedad con datos de ubicación",
      step4Title: "Revisar y enviar",
      step4Subtitle: "Revisa tu información antes de enviarla",
      uploadID: "Subir pasaporte o identificación",
      uploadIDDescription: "Por favor sube una foto clara de tu pasaporte o cédula de identidad emitida por el gobierno",
      dragDrop: "Arrastra y suelta tu identificación aquí, o haz clic para buscar",
      supportedFormats: "Formatos soportados: JPG, PNG, PDF (máx 10MB)",
      faceVerification: "Verificación facial",
      faceVerificationDescription: "Tómate una selfie para verificar que tu identidad coincida con tu documento de identidad",
      startCamera: "Iniciar cámara",
      retakePhoto: "Volver a tomar foto",
      photoLooksGood: "¡La foto se ve bien!",
      propertyPhotos: "Fotos de la propiedad",
      propertyPhotosDescription: "Sube 2 fotos de alta calidad de tu propiedad. Los datos de ubicación se capturarán automáticamente.",
      photo: "Foto",
      uploadPhoto: "Subir foto",
      locationCaptured: "Ubicación capturada",
      locationRequired: "Datos de ubicación requeridos - por favor habilita los servicios de ubicación",
      allPhotosRequired: "Se requieren las 2 fotos",
      reviewInfo: "Revisa tu información",
      personalDetails: "Detalles personales",
      verificationStatus: "Estado de verificación",
      verified: "Verificado",
      pending: "Revisión pendiente",
      propertyDetails: "Detalles de la propiedad",
      photosUploaded: "fotos subidas",
      locationVerified: "Ubicación verificada",
      submit: "Enviar para revisión",
      submitting: "Enviando...",
      successTitle: "¡Solicitud enviada!",
      successMessage: "Estamos revisando tu solicitud. Recibirás noticias nuestras en 24-48 horas.",
      goToDashboard: "Ir al panel",
      continue: "Continuar",
      back: "Atrás",
      skip: "Saltar por ahora",
    },
    hostDashboard: {
      welcome: "Bienvenido de nuevo",
      dashboard: "Panel",
      bookings: "Reservas",
      earnings: "Ganancias",
      messages: "Mensajes",
      property: "Propiedad",
      settings: "Configuración",
      logout: "Cerrar sesión",
      upcomingBookings: "Próximas reservas",
      pastBookings: "Reservas pasadas",
      noBookings: "Aún no hay reservas",
      checkIn: "Entrada",
      checkOut: "Salida",
      guests: "Huéspedes",
      total: "Total",
      pending: "Pendiente",
      confirmed: "Confirmado",
      cancelled: "Cancelado",
      viewDetails: "Ver detalles",
      messageGuest: "Mensaje al huésped",
      totalEarnings: "Ganancias totales",
      thisMonth: "Este mes",
      lastMonth: "Mes pasado",
      available: "Disponible para pago",
      requestPayout: "Solicitar pago",
      payoutHistory: "Historial de pagos",
      date: "Fecha",
      amount: "Cantidad",
      status: "Estado",
      paid: "Pagado",
      processing: "Procesando",
      recentMessages: "Mensajes recientes",
      newMessage: "Nuevo mensaje",
      typeMessage: "Escribe tu mensaje...",
      send: "Enviar",
      propertyStats: "Estadísticas de la propiedad",
      views: "Vistas",
      bookingRate: "Tasa de reserva",
      avgRating: "Calificación promedio",
      responseTime: "Tiempo de respuesta",
      hours: "horas",
      updateProperty: "Actualizar propiedad",
      manageAvailability: "Gestionar disponibilidad",
      quickActions: "Acciones rápidas",
      totalBookings: "Reservas totales",
      activeListings: "Anuncios activos",
      pendingPayouts: "Pagos pendientes",
    },
    hostPricing: {
      title: "Panel de administración del anfitrión",
      subtitle: "Gestiona tus precios y fotos del anuncio",
      pricing: "Precios",
      photos: "Fotos",
      baseRate: "Tarifa base",
      baseRateDescription: "Establece tu precio nocturno predeterminado",
      basePricePerNight: "Precio base por noche",
      calendarPricing: "Precios del calendario",
      pricingRules: "Reglas de precios",
      addRule: "Agregar regla",
      noRules: "Aún no hay reglas de precios",
      clickToAdd: "Haz clic en + para agregar una regla",
      customPrices: "Precios personalizados",
      uploadPhotos: "Subir fotos del anuncio",
      uploadDescription: "Sube imágenes de alta calidad de tu propiedad. Formatos compatibles: JPG, PNG, WebP (máx 10MB cada una)",
      chooseFiles: "Elegir archivos",
      photoGallery: "Galería de fotos",
      carousel: "Carrusel",
      viewAdvert: "Ver anuncio",
      noPhotos: "Aún no hay fotos subidas",
      uploadToSee: "Sube fotos para verlas aquí",
      yourListing: "Tu anuncio de propiedad",
      previewDescription: "Así es como aparecerá tu anuncio en el sitio web",
      pricePerNight: "Precio por noche",
      rating: "Calificación",
      photosUploaded: "fotos subidas",
      photo: "foto",
      setCustomPrice: "Establecer precio personalizado",
      date: "Fecha",
      currentPrice: "Precio actual",
      customPriceLabel: "Precio personalizado ($)",
      reasonOptional: "Motivo (Opcional)",
      savePrice: "Guardar precio",
      addPricingRule: "Agregar regla de precios",
      editPricingRule: "Editar regla de precios",
      ruleName: "Nombre de la regla",
      type: "Tipo",
      value: "Valor",
      startDate: "Fecha de inicio",
      endDate: "Fecha de finalización",
      appliesTo: "Se aplica a",
      allDays: "Todos los días",
      weekendsOnly: "Solo fines de semana",
      weekdaysOnly: "Solo días laborables",
      holidaysOnly: "Solo días festivos",
      percentageIncrease: "Aumento/Decremento porcentual",
      fixedPrice: "Precio fijo",
      discount: "Descuento (%)",
      preview: "Vista previa",
      afterRule: "Después de la regla",
      updateRule: "Actualizar regla",
      addRuleButton: "Agregar regla",
      cancel: "Cancelar",
      lastUpdated: "Última actualización",
      justNow: "Ahora mismo",
    },
    hostMessages: {
      title: "Mensajes",
      subtitle: "Comunícate con tus huéspedes",
      allMessages: "Todos los mensajes",
      unread: "No leídos",
      archived: "Archivados",
      searchMessages: "Buscar mensajes...",
      newConversation: "Nueva conversación",
      selectGuest: "Selecciona un huésped para comenzar a mensajear",
      guestName: "Nombre del huésped",
      bookingDates: "Fechas de reserva",
      attachFile: "Adjuntar archivo",
      sendMessage: "Enviar mensaje",
      online: "En línea",
      offline: "Desconectado",
      typing: "escribiendo...",
      lastSeen: "Visto por última vez",
      markAsRead: "Marcar como leído",
      archive: "Archivar",
      delete: "Eliminar",
      noMessages: "Aún no hay mensajes",
      startConversation: "Inicia una conversación con tus huéspedes",
    },
  },
};

export function getText(key: string, lang: string = "en"): string {
  const keys = key.split(".");
  let value: any = text[lang as keyof typeof text];

  for (const k of keys) {
    value = value?.[k];
  }

  return value || key;
}
